In [2]:
import hdf5storage
import os
import pandas as pd
import numpy as np
import matplotlib as mpl
import matplotlib.pyplot as plt

In [3]:
# global setting f
plt.rcParams.update({'font.size': 17})
mpl.rcParams['lines.markersize'] = 8

In [20]:
# top level dir 
# 

PROJECT_DIR = "/data/rwchain-all/round2"
BEH_DIR = os.path.join(PROJECT_DIR, "rwchain-beh/data")
EEG_DIR = os.path.join(PROJECT_DIR, "rwchain-eeg")

list_of_subj = os.listdir(BEH_DIR)
list_of_subj.sort()
# list_of_subj = [list_of_subj[5]]

In [21]:
# read and concatenance .csv file of the behavioral data
for subj in list_of_subj:
    BEH_DIR_SUBJ = os.path.join(BEH_DIR, subj)
    flist_beh = os.listdir(BEH_DIR_SUBJ)

    onlyfile_s1 = [f for f in flist_beh if subj in f and 'csv' in f and 'ses1' in f]
    onlyfile_s2 = [f for f in flist_beh if subj in f and 'csv' in f and 'ses2' in f]

    onlyfile_s1.sort()
    onlyfile_s2.sort()
    print(subj)
    # print(onlyfile_s1)
    # print(onlyfile_s2)
    print(len(onlyfile_s1), 'files found session 1')
    print(len(onlyfile_s2), 'files found session 2')
    if len(onlyfile_s2) != 10:
        print('missing files!')
    df = []


    for f in onlyfile_s1:
        fname = os.path.join(BEH_DIR_SUBJ, f)
        blockdf = pd.read_csv(fname)
        blocknum = f[16]
        blockdf['block'] =  blocknum
        block_string = f'ses1_block_{blocknum}'
        fname_chain = [f for f in flist_beh if subj in f and 'chains' in f and block_string in f]
        chain_array = pd.read_pickle(os.path.join(BEH_DIR_SUBJ, fname_chain[0]))
        blockdf['sequence_clean'] = chain_array.tolist()
        df.append(blockdf)
    for f in onlyfile_s2:
        fname = os.path.join(BEH_DIR_SUBJ, f)
        blockdf = pd.read_csv(fname)
        blocknum = f[16]
        blockdf['block'] =  blocknum
        block_string = f'ses2_block_{blocknum}'
        fname_chain = [f for f in flist_beh if subj in f and 'chains' in f and block_string in f]
        chain_array = pd.read_pickle(os.path.join(BEH_DIR_SUBJ, fname_chain[0]))
        blockdf['sequence_clean'] = chain_array.tolist()
        df.append(blockdf)
    df = pd.concat(df)
    file_path = os.path.join(BEH_DIR_SUBJ, f'{subj}_df_concat.csv')
    df.to_csv(file_path, index=False) 


s102
5 files found session 1
10 files found session 2
s103
10 files found session 1
10 files found session 2
s105
9 files found session 1
10 files found session 2
s106
10 files found session 1
10 files found session 2
s107
10 files found session 1
10 files found session 2
s108
5 files found session 1
10 files found session 2
s109
10 files found session 1
5 files found session 2
missing files!
s110
10 files found session 1
10 files found session 2
s112
10 files found session 1
10 files found session 2
s113
10 files found session 1
10 files found session 2


In [77]:
os.path.join(BEH_DIR_SUBJ, fname_chain)

TypeError: join() argument must be str, bytes, or os.PathLike object, not 'list'

In [63]:
    fname = os.path.join(BEH_DIR_SUBJ, f)
    blockdf = pd.read_csv(fname)
    blocknum = f[16]
    blockdf['block'] =  blocknum
    block_string = f'ses1_block_{blocknum}'
    fname_chain = [f for f in flist_beh if subj in f and 'chains' in f and 'ses1' in f]

In [64]:
fname_chain

['s103_ses1_block_4_chains',
 's103_ses1_block_1_chains',
 's103_ses1_block_2_chains',
 's103_ses1_block_8_chains',
 's103_ses1_block_0_chains',
 's103_ses1_block_5_chains',
 's103_ses1_block_7_chains',
 's103_ses1_block_3_chains',
 's103_ses1_block_6_chains',
 's103_ses1_block_9_chains']

In [87]:
np.where((np.array(converted_array)*1000 - data['rt'])>100)

(array([22, 44, 45, 49]),)

In [67]:
np.array(converted_array) - data['rt']

array([31., 30., 29., 29., 30., 30., 30., 30., 30., nan, 29., 30., 29.,
       31., 30., 30., 30., 30., 30., 30., 30., 30., 30., 30., 30., 30.,
       31., 30., 30., 30., 30., 30., 30., 30., 30., 30., 30., 30., 30.,
       29., 29., 30., 30., nan, 30., 29., 31., 30., 30., 30.])

In [25]:
flist_beh[20]

'102_ses2_block_6_chains'

In [32]:
fname = os.path.join(BEH_DIR_SUBJ, flist_beh[20])
pd.read_pickle(fname)[2]

array([ 1.,  1., -1., -1.,  1., -1., -1.,  1.,  1., -1.,  1., -1.,  1.,
        1., -1.,  1., -1., -1., -1., -1., -1., -1., -1.,  1.,  1.,  1.,
       -1., -1., -1., -1.])

In [46]:
fname2 = os.path.join(BEH_DIR_SUBJ, '102_ses2_block_6.csv')
df = pd.read_csv(fname2)

In [27]:
[i for i  in flist_beh if 'block_6' in i]

['102_ses2_block_6_chains', '102_ses2_block_6.csv']

In [7]:
os.path.join(PROJECT_DIR, BEH_DIR, subj)

'/data/rwchain-all/round2/rwchain-beh/s102'

In [14]:
fname = os.path.join(BEH_DIR_SUBJ, flist[0])
df = pd.read_csv(fname)

In [16]:
df['sequence']

0     [-1.  1. -1.  1. -1.  1. -1. -1. -1. -1. -1.  ...
1     [-1. -1. -1.  1.  1.  1.  1.  1. -1. -1. -1. -...
2     [ 1. -1. -1. -1.  1.  1. -1. -1. -1. -1.  1.  ...
3     [ 1.  1.  1.  1. -1.  1.  1. -1. -1. -1.  1. -...
4     [-1.  1. -1.  1.  1. -1.  1.  1.  1. -1. -1. -...
5     [ 1.  1.  1. -1. -1.  1.  1.  1. -1.  1.  1.  ...
6     [ 1. -1.  1.  1.  1. -1. -1.  1. -1. -1.  1. -...
7     [ 1. -1.  1.  1.  1.  1.  1.  1. -1. -1.  1. -...
8     [-1.  1.  1. -1.  1. -1.  1. -1. -1. -1. -1. -...
9     [-1.  1. -1.  1. -1. -1.  1. -1.  1.  1.  1. -...
10    [ 1. -1.  1. -1. -1. -1.  1. -1.  1.  1. -1.  ...
11    [-1.  1.  1.  1.  1.  1.  1. -1.  1.  1.  1.  ...
12    [ 1. -1.  1.  1. -1.  1. -1.  1.  1. -1.  1. -...
13    [ 1. -1. -1.  1. -1.  1.  1. -1.  1. -1. -1.  ...
14    [-1.  1.  1.  1. -1. -1.  1.  1. -1. -1. -1. -...
15    [-1.  1. -1.  1.  1. -1.  1. -1. -1.  1.  1.  ...
16    [-1.  1. -1. -1.  1. -1. -1. -1. -1. -1. -1. -...
17    [ 1.  1.  1. -1.  1.  1.  1.  1.  1.  1.  

In [23]:
df

time  bytetime press  count  key  stimDur  Bias  \
0   2.616668      2611   [1]     10  [2]     0.25  0.12   
1   2.249989      2233   [1]      8  [5]     0.25  0.12   
2   2.133332      2118   [1]      8  [2]     0.25  0.12   
3   1.283374      1270   [1]      5  [5]     0.25  0.12   
4   2.333314      2318   [1]      9  [5]     0.25  0.12   
5   1.249995      1247   [1]      4  [5]     0.25  0.12   
6   1.499987      1494   [1]      5  [5]     0.25  0.12   
7   1.533322      1531   [1]      6  [5]     0.25  0.12   
8   2.616660      7026   [1]     10  [2]     0.25  0.12   
9   3.066638     12978   [1]     12  [5]     0.25  0.12   
10  2.116638     17662   [1]      8  [2]     0.25  0.12   
11  1.466668     21560   [1]      5  [5]     0.25  0.12   
12  2.533332     26707   [1]     10  [5]     0.25  0.12   
13  2.416645     31892   [1]      9  [5]     0.25  0.12   
14  3.099993     37520   [1]     12  [2]     0.25  0.12   
15  3.349968     43353   [1]     13  [5]     0.25  0.12   
16  2.283320     48229   [1]      9  [2]     0.25  0.12   
17  1.100000     51711   [1]      4  [5]     0.25  0.12   
18  2.633314     57160   [1]     10  [5]     0.25  0.12   
19  2.066651     61848   [1]      8  [2]     0.25  0.12   
20  2.083300     66318   [1]      8  [2]     0.25  0.12   
21  1.133381     70174   [1]      4  [2]     0.25  0.12   
22  1.783364     74322   [1]      7  [2]     0.25  0.12   
23  1.749984     78763   [1]      6  [5]     0.25  0.12   
24  1.916612     83193   [1]      7  [2]     0.25  0.12   
25  2.149986     87921   [1]      8  [5]     0.25  0.12   
26  2.466684     93078   [1]      9  [5]     0.25  0.12   
27  1.616657     96864   [1]      6  [2]     0.25  0.12   
28  1.683328    101144   [1]      6  [2]     0.25  0.12   
29  1.666655      1653   [1]      6  [2]     0.25  0.12   
30  2.533323      2519   [1]     10  [5]     0.25  0.12   
31  1.766654      1751   [1]      7  [5]     0.25  0.12   
32  2.033328      2030   [1]      8  [2]     0.25  0.12   
33  2.049986      2035   [1]      8  [2]     0.25  0.12   
34  3.066642      3066   [1]     12  [5]     0.25  0.12   
35  2.599993      2598   [1]     10  [5]     0.25  0.12   
36  1.700006      1687   [1]      6  [2]     0.25  0.12   
37  1.350034      1339   [1]      5  [5]     0.25  0.12   
38  2.316635      2309   [1]      9  [5]     0.25  0.12   
39  1.466669      1464   [1]      5  [2]     0.25  0.12   
40  4.049886      4045   [1]     16  [2]     0.25  0.12   
41  1.116660      1111   [1]      4  [2]     0.25  0.12   
42  1.233348      1223   [1]      4  [5]     0.25  0.12   
43  1.433329      1423   [1]      5  [5]     0.25  0.12   
44  2.533316      2525   [1]     10  [5]     0.25  0.12   
45  1.749993      1735   [1]      6  [5]     0.25  0.12   
46  3.616628      3611   [1]     14  [2]     0.25  0.12   
47  2.033330      2030   [1]      8  [2]     0.25  0.12   
48  2.499981      2490   [1]      9  [5]     0.25  0.12   
49  1.649988      1640   [1]      6  [2]     0.25  0.12   

                                             sequence  
0   [-1.  1. -1.  1. -1.  1. -1. -1. -1. -1. -1.  ...  
1   [-1. -1. -1.  1.  1.  1.  1.  1. -1. -1. -1. -...  
2   [ 1. -1. -1. -1.  1.  1. -1. -1. -1. -1.  1.  ...  
3   [ 1.  1.  1.  1. -1.  1.  1. -1. -1. -1.  1. -...  
4   [-1.  1. -1.  1.  1. -1.  1.  1.  1. -1. -1. -...  
5   [ 1.  1.  1. -1. -1.  1.  1.  1. -1.  1.  1.  ...  
6   [ 1. -1.  1.  1.  1. -1. -1.  1. -1. -1.  1. -...  
7   [ 1. -1.  1.  1.  1.  1.  1.  1. -1. -1.  1. -...  
8   [-1.  1.  1. -1.  1. -1.  1. -1. -1. -1. -1. -...  
9   [-1.  1. -1.  1. -1. -1.  1. -1.  1.  1.  1. -...  
10  [ 1. -1.  1. -1. -1. -1.  1. -1.  1.  1. -1.  ...  
11  [-1.  1.  1.  1.  1.  1.  1. -1.  1.  1.  1.  ...  
12  [ 1. -1.  1.  1. -1.  1. -1.  1.  1. -1.  1. -...  
13  [ 1. -1. -1.  1. -1.  1.  1. -1.  1. -1. -1.  ...  
14  [-1.  1.  1.  1. -1. -1.  1.  1. -1. -1. -1. -...  
15  [-1.  1. -1.  1.  1. -1.  1. -1. -1.  1.  1.  ...  
16  [-1.  1. -1. -1.  1. -1. -1. -1. -1. -1. -